id: P010474
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-19 20:51:42.791587
source_metadata:
  id: bdr:W1PD137852
  title: ཨ་མདོའི་གཏམ་དཔེ་མཁས་པའི་མགྲིན་རྒྱན།
  author: ''
  volumes:
    92c9c75c52ec4494bf31dbdd83ca305e:
      image_group_id: I2PD19648
      title: ''
      volume_number: 1
      total_pages: 216
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
