id: P010474
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD137852
  title: ཨ་མདོའི་གཏམ་དཔེ་མཁས་པའི་མགྲིན་རྒྱན།
  author: ''
  volumes:
    92c9c75c52ec4494bf31dbdd83ca305e:
      image_group_id: I2PD19648
      title: ''
      volume_number: 1
      total_pages: 216
      base_file: v001.txt
